### ISSUE TITLE
"list" widgets are not present in fields.frontmattermd

### ISSUE THREAD

**Issue by DavrosFl** [WhiteAbeLincoln/gatsby-transformer-remark-frontmatter#2]
Does this plugin work with list widgets? They are not available in fields for me. Is there a work-around for this?

For example, in the below .md file, servicesHeader is present in fields.frontmattermd, but not serviceList. 
```
---
servicesHeader: A services header
serviceList:
  - service:
      serviceCopy: >-
        Some copy
      serviceName: A Service Name
  - service:
      serviceCopy: >-
        More Copy
      serviceName: Another service
---
```

The query:
```
{
  allFile(filter: {sourceInstanceName: {eq: "content"}, name: {eq: "services"}}) {
    edges {
      node {
        childMarkdownRemark {
          fields {
            frontmattermd {
              serviceList {
                htmlAst
              }
              servicesHeader {
                htmlAst
              }
            }
          }
          frontmatter {
            servicesTest
            servicesHeader
            serviceList {
              service {
                serviceName
                serviceCopy
              }
            }
          }
        }
      }
    }
  }
}
```

... produces error:
```
{
  "errors": [
    {
      "message": "Cannot query field \"serviceList\" on type \"MarkdownRemarkFieldsFrontmattermd\". Did you mean \"servicesHeader\"?",
      "locations": [
        {
          "line": 8,
          "column": 15
        }
      ],
      "stack": [
        "GraphQLError: Cannot query field \"serviceList\" on type \"MarkdownRemarkFieldsFrontmattermd\". Did you mean \"servicesHeader\"?",
        "    at Object.Field (/Users/auser/project/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:53:31)",
        "    at Object.enter (/Users/auser/project/node_modules/graphql/language/visitor.js:324:29)",
        "    at Object.enter (/Users/auser/project/node_modules/graphql/language/visitor.js:375:25)",
        "    at visit (/Users/project/auser/node_modules/graphql/language/visitor.js:242:26)",
        "    at validate (/Users/auser/project/node_modules/graphql/validation/validate.js:73:24)",
        "    at getGraphQLParams.then.then.optionsData (/Users/auser/project/node_modules/express-graphql/index.js:121:32)",
        "    at processTicksAndRejections (internal/process/next_tick.js:81:5)"
      ]
    }
  ]
}
```

**Comment by ttstauss** [comment]
I'm facing a similar issue. It doesn't seem to pick up the frontmatter fields. The only fields being picked up are those queried in gatsby-node.js. I expected it to include all frontmatter fields (unless a whitelist/blacklist is dictated) from the .md files. Are we missing something?

**Comment by WhiteAbeLincoln** [comment]
No the plugin doesn't recursively travel through lists or objects in the frontmatter to generate markdown, it only handles top-level frontmatter keys with a string value. I haven't needed this functionality, but I'd be happy to accept a pull request. It shouldn't be too difficult, we just need another check at https://github.com/WhiteAbeLincoln/gatsby-transformer-remark-frontmatter/blob/6001fe7e374fafc4e48e965840f7083df65f5f8f/src/gatsby-node.ts#L128 which tests whether the node is an object or list and iterates down that. More difficult would be saving the paths as we traverse the node and ensuring the created fields#frontmattermd path is the same.

@ttstauss I'm not sure what your issue is. I'm not able to reproduce, fields that aren't queried in my gatsby-node file still show up under the frontmattermd field in the GraphiQL explorer. If you still have more problems, please open another issue with some minimal code that can reproduce the issue

**Comment by WhiteAbeLincoln** [comment]
This should be possible by using the 'md' directive with version 1.1.0 (and 1.0.1 for that matter).
